#+TITLE: Decision 2020: An Election Night Support Zoom Hugbox
#+OPTIONS: toc:nil num:nil html-postamble:nil
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="static/tufte.css" \>

#+begin_export html
<style>
h3 {font-style: normal;
    font-weight: bold;}
img {max-width: 80%;}
body {padding-left: 5.25%;}
</style>
#+end_export

* You're invited!
  Election nights used to mean gathering for watch parties, booing and cheering states as appropriate, and chowing down on nachos. With this year looking more like a sit nervously in your apartment stress-eating a whole thing of peanut butter M&Ms kind of situation, I'm inviting YOU to an exclusive digital online election night event! The night will feature:
** Awkward silences as we all doomscroll!
** Eating junk food but not in a fun way!
** LIVE analysis from our newscoffeetable! Featured analysts include:
   -  Nathan Saritzky, a guy with enough free time to read everything there is to know about the election
   - Sophie, a very fluffy cat who has her paws on the pulse of the nation
   - This picture of Tim Russert
   file:static/florida.jpg
** Probably not even knowing the result!
  So don't miss this once-in-a-lifetime (god I hope) opportunity! Feel free to drop in and out as your are willing and emotionally able.
** [[https://meet.google.com/ryh-rxtf-cnc][Join here!]]
